language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t vgrechin/docker-react -f Dockerfile.dev .

script:
  - npm install && docker run -e CI=true -v $(pwd):/usr/app vgrechin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "eu-north-1"
  app: "DockerReact"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-eu-north-1-334453841210
  bucket_path: "DockerReact"
  on:
    branch: master

