language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t vgrechin/docker-react -f Dockerfile.dev .

script:
  - npm install && docker run -e CI=true -v $(pwd):/usr/app vgrechin/docker-react npm run test